### ISSUE TITLE
[csp] --skip-prod-url 

### ISSUE THREAD

**Issue by brandonneil** [ITS-UofIowa/nile#120]
For when we move sites between docroots, it would be nice during cloud site provision for the second site to be able to do one without attempting to create the production external domain.

I think adding a `--skip-prod-url` option could do that.

**Comment by genjohnson** [comment]
I think this functionality would be a nice addition, and it would also be useful in the case of provisioning a test site for which we will never use a production domain (I've just run into this use case for the Standard service). 

I'm wondering if naming the option `--skip-prod-domain` would be more natural, since we are all referring to the URLs listed in Acquia's interface as domains (and that's the terminology Acquia uses).

**Comment by richardbporter** [comment]
This is necessary because the command will fail without completing the provisioning process if a domain already exists. We could change it to fail gracefully but this task feeds into a larger discussion on if sites should be allowed to exist in dev/stage/prod independently.
