### ISSUE TITLE
Implement local:site-deprovision command

### ISSUE THREAD

**Issue by richardbporter** [ITS-UofIowa/nile#84]

**Comment by genjohnson** [comment]
These are the steps I have taken to manually deprovision local sites:
1. Delete the website in DevDesktop using the GUI. (This deletes the database and removes the site from the list of sites in the multisite.)
2. Delete the drush alias file in `/acquia/[application]/drush/site-aliases`
3. Delete the site directory in `/acquia/[application]/docroot/sites`
4. Delete the site entry in `/acquia/[application]/library/.sites.local.yml`
5. Run `nile sgs library/.sites.local.yml local` from `/acquia/[application]` to re-generate sites.php, removing the entry for the site being deprovisioned.

**Comment by genjohnson** [comment]
Until [#84: Implement local:site-deprovision command](https://github.com/ITS-UofIowa/nile/issues/84) is resolved, I usually need to change permissions on the site directories before they can be deleted. I've been using `chmod u+wx *uiowa.edu`, which will target all of the site directories (since I tend to delete many sites at a time).

**Comment by richardbporter** [comment]
The local drush alias file should be deleted (step 2) after `nile sga` is run again (step 6).
