### ISSUE TITLE
limit domain name to 63 characters in CSP

### ISSUE THREAD

**Issue by richardbporter** [ITS-UofIowa/nile#86]
At least limit database names to 128 characters.

**Comment by brandonneil** [comment]
What do you think the best way to handle this will be? In https://github.com/ITS-UofIowa/nile/blob/master/src/Acquia/Multisite.php#L175 we use use the aliasGroup as part of the transformation to databaseName.

Do we just add a substr?:
` $this->databaseName = substr(str_replace("-", "_", "{$this->type}_{$this->aliasGroup}",0,128);`

**Comment by richardbporter** [comment]
Yea, I think that should work.

**Comment by brandonneil** [comment]
Looks like we don't need to worry about validating the database name, because the domain name is the smaller requirement:

> Domain names are limited to alphanumeric characters, dashes, and dots and cannot have more than 63 characters.

**Comment by brandonneil** [comment]
So instead of a substr, we should do a validation in the csp when you provide the domain name.

It looks like the spec is 63 characters per octet, so if Acquia follows that, we will have to break the string into an array based on each octet and ensure that one is not larger that 63 characters. https://tools.ietf.org/html/rfc2181#page-13

I plan to validate if acquia validates based on the octet or full domain.

**Comment by brandonneil** [comment]
It is 63 characters max. The form input does not allow for more.

**Comment by brandonneil** [comment]
We also will need to validate every value of `-additional-domains=ADDITIONAL-DOMAINS` as well as the value of the `-www` option
